### ISSUE TITLE
How to handle webmentions for non-canonical URL?

### ISSUE THREAD

**Issue by singpolyma** [converspace/webmention#43]
What if the source links to me using a shortlink (or other non-canonical link)?  Should they send a `target=` with the shortlink in it and then I resolve in order to find the content locally?  Should they send a `target=` with the resolved link in it... but then how do I do the verification?  Or is this sort of linking just not allowed?  Seems like it would be useful to allow it.

**Comment by aaronpk** [comment]
If the source HTML has a shortlink (or other non-canonical link) then the target parameter will also be the same link. It's up to the receiving website to resolve that to the canonical URL on their site.

This is discussed a little more on the wiki:

* http://indiewebcamp.com/webmention#Protocol_Summary
* http://indiewebcamp.com/webmention#must_follow_redirects
* http://indiewebcamp.com/webmention#Why_is_the_target_URL_a_required_parameter

The webmention receiver must follow redirects (or otherwise resolve) a non-canonical target parameter.
